/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FogLayer__factory } from "./FogLayer__factory";
export { Hospital__factory } from "./Hospital__factory";
