/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FogLayer } from "./FogLayer";
export type { Hospital } from "./Hospital";
export * as factories from "./factories";
export { Hospital__factory } from "./factories/Hospital__factory";
export { FogLayer__factory } from "./factories/FogLayer__factory";
